name = "ai-proxy-${{ github.run_id }}"
main = "src/index.js"
compatibility_date = "2025-10-31"

# 自动创建 KV
[[kv_namespaces]]
binding = "KV"
id = ""

[vars]
MODELS = '''
gpt-4o|openai|https://api.openai.com/v1/chat/completions
gpt-4o-mini|openai|https://api.openai.com/v1/chat/completions
gpt-3.5-turbo|openai|https://api.openai.com/v1/chat/completions
claude-3-5-sonnet-20241022|anthropic|https://api.anthropic.com/v1/messages
claude-3-opus-20240229|anthropic|https://api.anthropic.com/v1/messages
gemini-1.5-pro|gemini|https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent
gemini-1.5-flash|gemini|https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
grok-beta|xai|https://api.x.ai/v1/chat/completions
deepseek-chat|deepseek|https://api.deepseek.com/v1/chat/completions
qwen-max|qwen|https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
llama-3.1-70b|groq|https://api.groq.com/openai/v1/chat/completions
llama-3.1-8b|groq|https://api.groq.com/openai/v1/chat/completions
moonshot-v1-8k|moonshot|https://api.moonshot.cn/v1/chat/completions
glm-4|glm|https://open.bigmodel.cn/api/paas/v4/chat/completions
'''
